"""update balance group member model

Revision ID: 022153d16d51
Revises: d47ed0e33d34
Create Date: 2025-08-03 02:40:09.967653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022153d16d51'
down_revision: Union[str, Sequence[str], None] = 'd47ed0e33d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_group_members', sa.Column('market_participant_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('balance_group_members_metering_point_id_fkey'), 'balance_group_members', type_='foreignkey')
    op.create_foreign_key(None, 'balance_group_members', 'market_participant', ['market_participant_id'], ['id'])
    op.drop_column('balance_group_members', 'metering_point_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_group_members', sa.Column('metering_point_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'balance_group_members', type_='foreignkey')
    op.create_foreign_key(op.f('balance_group_members_metering_point_id_fkey'), 'balance_group_members', 'metering_point', ['metering_point_id'], ['id'])
    op.drop_column('balance_group_members', 'market_participant_id')
    # ### end Alembic commands ###
